version: '3'
services:
  task_sorter:
    image: task_sorter
    restart: always
    build:
      context: ./
    ports:
      - '1337:80'
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:80/"]
    interval: 2m
    timeout: 10s
    retries: 1
